# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  sotryMetadata_insert(
    data: {id: "11111111222233334444555555555555", storyId: "11111111222233334444555555555555", description: "", rating: 0, releaseYear: 0}
  )
}